name: Freedom_Guard
description: "Freedom Guard +x Freedom Vibe +x Freedom Link"
publish_to: 'none' 

version: 12.0.3+1 

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  dart_promise: ^0.0.1+1
  ffi: ^2.1.3
  flutter_v2ray_client:
    git:
      url: https://github.com/Freedom-Guard/vibe_core.git
  http: ^1.3.0
  synchronized: ^3.3.0+3
  clipboard: ^0.1.3
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.4
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  flutter_spinkit: ^5.2.1
  connectivity_plus: ^6.1.3
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.273
  package_info_plus: ^8.3.0
  app_manager: ^0.1.1
  installed_apps: ^1.6.0
  qr_flutter: ^4.1.0
  percent_indicator: ^4.2.5
  webview_flutter: ^4.11.0
  cloud_firestore: ^5.6.7
  uuid: ^4.5.1
  encrypt: ^5.0.3
  quick_settings:
    git:
      url: https://github.com/Freedom-Guard-Builder/quick_settings/
  fluttertoast: ^8.2.12
  firebase_core: ^3.5.0
  firebase_analytics: ^11.2.0
  firebase_in_app_messaging: ^0.8.1+10
  device_info_plus: ^12.1.0
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  dio: ^5.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.2.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/ico.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/

